import AxeBuilder from "@axe-core/playwright";
import { test, expect } from "@playwright/test";

test("password change, recovery and fresh login work through the UI", async ({ page }) => {
  const email = `account-${Date.now()}@example.test`;
  const registered = await page.request.post("/api/auth/register", { data: { email, name: "Хранитель", password: "old-password-123", passwordConfirmation: "old-password-123", countryName: "Мир хранителя", cityName: "Город хранителя" } });
  expect(registered.ok()).toBe(true);
  await page.goto("/");
  await page.getByLabel("Меню", { exact: true }).click();
  await page.getByRole("button", { name: "Аккаунт и настройки" }).click();
  await page.getByLabel("Текущий пароль", { exact: true }).fill("wrong-password");
  await page.getByLabel("Новый пароль", { exact: true }).fill("new-password-123");
  await page.getByLabel("Повторите новый пароль").fill("new-password-123");
  await page.getByRole("button", { name: "Сменить пароль" }).click();
  await expect(page.getByRole("alert")).toContainText("Текущий пароль неверен");
  await page.getByLabel("Текущий пароль", { exact: true }).fill("old-password-123");
  await page.getByRole("button", { name: "Сменить пароль" }).click();
  await expect(page.getByRole("button", { name: "Открыть страну" })).toBeVisible();
  await page.getByLabel("Email", { exact: true }).fill(email);
  await page.getByLabel("Пароль", { exact: true }).fill("new-password-123");
  await page.getByRole("button", { name: "Открыть страну" }).click();
  await page.getByLabel("Меню", { exact: true }).click();
  await page.getByRole("button", { name: "Аккаунт и настройки" }).click();
  await page.getByLabel("Текущий пароль", { exact: true }).fill("new-password-123");
  await page.getByText("Резервные коды восстановления", { exact: true }).click();
  await page.getByRole("button", { name: "Получить новый набор кодов" }).click();
  const code = (await page.getByLabel("Резервные коды", { exact: true }).innerText()).split("\n")[0]!;
  await page.getByRole("button", { name: "Выйти из аккаунта" }).click();
  await page.getByRole("button", { name: "Забыли пароль?" }).click();
  await page.getByLabel("Email", { exact: true }).fill(email);
  await page.setViewportSize({ width: 390, height: 844 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  expect((await new AxeBuilder({ page }).analyze()).violations.filter(v => v.impact === "serious" || v.impact === "critical")).toEqual([]);
  await page.screenshot({ path: "test-results/account-recovery-mobile.png" });
  await page.getByLabel("Резервный код", { exact: true }).fill(code);
  await page.getByLabel("Новый пароль", { exact: true }).fill("restored-password-123");
  await page.getByLabel("Повторите новый пароль").fill("restored-password-123");
  await page.getByRole("button", { name: "Восстановить доступ" }).click();
  await expect(page.getByRole("status")).toContainText("Пароль изменён");
  await page.getByRole("button", { name: "Вернуться ко входу" }).click();
  await page.getByLabel("Email", { exact: true }).fill(email);
  await page.getByLabel("Пароль", { exact: true }).fill("restored-password-123");
  await page.getByRole("button", { name: "Открыть страну" }).click();
  await expect(page.locator(".country-title-button")).toBeVisible();
});

test("owner creates a link for a new user who registers and accepts it", async ({ page, browser }, info) => {
  await page.request.post("/api/auth/login", { data: { email: "demo@tasktopia.local", password: "tasktopia-demo" } });
  await page.goto("/");
  await page.locator(".country-title-button").click();
  await page.getByRole("button", { name: "Паспорт страны", exact: true }).click();
  await page.getByText("Приглашения по ссылке", { exact: true }).click();
  const email = `invited-${Date.now()}@example.test`;
  await page.getByLabel("Email приглашённого").fill(email);
  await page.getByRole("button", { name: "Создать ссылку", exact: true }).click();
  const link = await page.getByLabel("Ссылка приглашения").inputValue();
  const guest = await browser.newContext({ baseURL: String(info.project.use.baseURL) });
  const visitor = await guest.newPage();
  await visitor.goto(link);
  await visitor.getByRole("button", { name: "Нет аккаунта? Зарегистрироваться" }).click();
  await visitor.getByLabel("Имя", { exact: true }).fill("Новый житель");
  await visitor.getByLabel("Email", { exact: true }).fill(email);
  await visitor.getByLabel("Название вашей первой страны").fill("Личный мир");
  await visitor.getByLabel("Название первого города").fill("Личный город");
  await visitor.getByLabel("Пароль", { exact: true }).fill("password-123");
  await visitor.getByLabel("Повторите пароль", { exact: true }).fill("password-123");
  await visitor.getByRole("button", { name: "Создать аккаунт" }).click();
  await visitor.getByRole("button", { name: "Принять приглашение" }).click();
  await expect(visitor.locator(".country-title-button")).toContainText("Тестовая страна");
  await guest.close();
});
