import { expect,test } from "@playwright/test";
import { transportAtlasFixture } from "../fixtures/atlas-transport";
import { transportSchedule,TRANSPORT_EPOCH } from "../../src/shared/transport-schedule";
import { projectPlanetAtlas } from "../../src/shared/planet-atlas";
import { buildPlanetSurfaceTransport } from "../../src/shared/planet-surface-transport";
test("PLANET preserves the server-scheduled consist and honour reduced motion",async({page},info)=>{
  test.skip(!/^http:\/\/(127\.0\.0\.1|localhost):/.test(process.env.E2E_BASE_URL??""),"Local visual fixture only");
  const errors:string[]=[];page.on("pageerror",error=>errors.push(error.message));
  await page.request.post("/api/auth/login",{data:{email:"demo@tasktopia.local",password:"tasktopia-demo"}});
  const atlas=transportAtlasFixture();
  const route=buildPlanetSurfaceTransport(projectPlanetAtlas(atlas)).rails.find(route=>route.id==="rail:station-0-0:station-0-1")!;
  expect(route).toBeDefined();
  const schedule=transportSchedule("RAIL",route.fromStationId,route.toStationId,route.scheduleOffsetMs);
  let started=performance.now(),anchor=TRANSPORT_EPOCH-schedule.offsetMs+schedule.dwellMs+schedule.travelMs*.4;
  await page.clock.setFixedTime(new Date("2035-01-01"));
  await page.route("**/api/**",async route=>{
    const response=await route.fetch();
    const headers={...response.headers(),"cache-control":"private, no-store","x-tasktopia-server-time":String(anchor+performance.now()-started)};
    if(route.request().url().endsWith("/planet-atlas"))await route.fulfill({response,headers,json:atlas});
    else await route.fulfill({response,headers});
  });
  await page.goto("/");
  const fleet=page.locator(`.atlas-train[data-route-id="${schedule.id}"]`);
  await expect(fleet).toHaveCount(schedule.fleetSize);
  const planet=page.locator(`.atlas-train[data-vehicle-id="${schedule.id}:vehicle:0"]`);
  await expect(planet).toBeVisible();await expect(planet.locator("image")).toHaveCount(6);
  const after=Number(await planet.getAttribute("data-progress"));expect(after).toBeGreaterThan(.35);expect(after).toBeLessThan(.6);
  const planetZoom=await page.locator(".planet-atlas").getAttribute("data-globe-zoom");
  const box=await planet.boundingBox();await page.mouse.move(box!.x+box!.width/2,box!.y+box!.height/2);await page.mouse.wheel(0,-250);
  await expect.poll(()=>page.locator(".planet-atlas").getAttribute("data-globe-zoom")).not.toBe(planetZoom);
  await page.screenshot({path:info.outputPath("planet-train.png")});
  await page.emulateMedia({reducedMotion:"reduce"});await expect(planet).toBeHidden();
  await page.emulateMedia({reducedMotion:"no-preference"});await expect(planet).toBeVisible();
  expect(Number(await planet.getAttribute("data-progress"))).toBeGreaterThanOrEqual(after);
  anchor=TRANSPORT_EPOCH-schedule.offsetMs+schedule.dwellMs+schedule.travelMs+2000;started=performance.now();
  await page.reload();
  await expect(planet).toHaveAttribute("data-phase","STOPPED");
  await expect(page.locator(".planet-atlas")).toHaveAttribute("data-planet-ready","true");
  const stopped=await planet.locator("image").first().getAttribute("transform");
  expect(stopped).toMatch(/^translate\(/);
  await page.evaluate(()=>new Promise<void>(resolve=>requestAnimationFrame(()=>requestAnimationFrame(()=>resolve()))));
  expect(await planet.locator("image").first().getAttribute("transform")).toBe(stopped);
  expect(errors).toEqual([]);
});
