import { openMapCity, openMapPlanet } from "./map-navigation";
import { expect, test } from '@playwright/test';

test('планета открывает город напрямую и сохраняет камеру без фоновой сцены', async ({page},testInfo)=>{
  test.setTimeout(120_000);
  const requests:string[]=[], errors:string[]=[];
  page.on('request',r=>requests.push(new URL(r.url()).pathname));
  page.on('pageerror',e=>errors.push(e.message));
  await page.goto('/');
  await page.getByLabel('Email').fill('demo@tasktopia.local');
  await page.getByLabel('Пароль').fill('tasktopia-demo');
  requests.length=0;
  await page.getByRole('button',{name:'Открыть страну',exact:true}).click();
  const planet=page.locator('.planet-atlas');
  await expect(planet).toHaveAttribute('data-planet-ready','true',{timeout:45_000});
  await expect(page.getByRole('navigation',{name:'Уровень карты'}).getByRole('button',{name:'Страна',exact:true})).toHaveCount(0);
  await expect(page.locator('.world-canvas')).toHaveCount(0);
  expect(requests.filter(p=>p.endsWith('/scene'))).toHaveLength(0);
  expect(requests.filter(p=>p.includes('/buildings/')&&p.endsWith('.png'))).toHaveLength(0);
  const target=page.locator('.planet-city-targets [data-city-id]').first();
  await target.click();
  await expect.poll(()=>planet.getAttribute('data-globe-zoom')).toBe('3.00');
  const camera=await planet.getAttribute('data-globe-zoom');
  await page.screenshot({path:'.builder/evidence/planet-close.png'});
  await page.getByRole('button',{name:'Открыть город Riverside',exact:true}).last().click();
  const world=page.locator('.world-canvas');
  await expect(world).toHaveAttribute('data-city-scene-commit','atomic',{timeout:60_000});
  await expect(page.locator('.map-level-transition')).toHaveCount(0,{timeout:20_000});
  const original=await page.locator('.world-canvas-element').elementHandle();
  const n=requests.filter(p=>p.endsWith('/scene')).length;
  expect(n).toBe(1);
  await page.screenshot({path:'.builder/evidence/city-entry.png'});
  await openMapPlanet(page);
  await expect(planet).toBeVisible();
  await expect(planet).toHaveAttribute('data-globe-zoom',camera!);
  await openMapCity(page);
  await expect(world).toBeVisible();
  expect(await original!.evaluate(node=>node===document.querySelector('.world-canvas-element'))).toBe(true);
  const box=(await world.boundingBox())!;
  await page.mouse.move(box.x+box.width*.7,box.y+box.height*.6);await page.mouse.down();await page.mouse.move(box.x+box.width*.3,box.y+box.height*.4,{steps:8});await page.mouse.up();
  expect(requests.filter(p=>p.endsWith('/scene'))).toHaveLength(n);
  expect(requests.filter(p=>p.startsWith('/api/chunks/')||p==='/api/world/viewport')).toHaveLength(0);
  expect(errors).toEqual([]);
  await testInfo.attach('navigation-network',{body:Buffer.from(JSON.stringify({sceneRequests:n,errors},null,2)),contentType:'application/json'});
});
