import { expect, test } from "@playwright/test";
import { mkdir } from "node:fs/promises";

// Runs against the isolated seed:test country, never a production fixture.
test("map navigation, labels and task controls follow the revised visual contract", async ({ page }) => {
  await mkdir("screenshots/visual-consistency", { recursive: true });
  await page.clock.setFixedTime(new Date("2026-09-08T10:00:00Z"));
  const errors: string[] = [];
  page.on("pageerror", error => errors.push(error.message));
  page.on("console", message => { if (message.type() === "error") errors.push(message.text()); });
  page.on("response", response => { if (response.status() >= 400 && !response.url().includes("/push/")) errors.push(`${response.status()} ${new URL(response.url()).pathname}`); });
  expect((await page.request.post("/api/auth/login", { data: { email: "demo@tasktopia.local", password: "tasktopia-demo" } })).ok()).toBe(true);
  await page.goto("/");
  const city = page.locator(".world-canvas");
  await expect(city).toHaveAttribute("data-city-scene-commit", "atomic", { timeout: 60_000 });
  await expect(page.getByRole("button", { name: "Границы", exact: true })).toHaveCount(0);
  await page.getByRole("button", { name: "Районы", exact: true }).click();
  await expect(page.getByRole("button", { name: "Районы", exact: true })).toHaveAttribute("aria-pressed", "true");
  await page.getByRole("button", { name: "Город", exact: true }).click();
  await expect(page.getByRole("button", { name: "Районы", exact: true })).toHaveAttribute("aria-pressed", "false");
  const initialX = await city.getAttribute("data-camera-world-x");
  const box = (await city.boundingBox())!;
  await page.mouse.move(box.x + box.width / 2, box.y + box.height / 2);
  await page.mouse.down(); await page.mouse.move(box.x + box.width / 2 + 100, box.y + box.height / 2, { steps: 8 }); await page.mouse.up();
  await expect.poll(() => city.getAttribute("data-camera-world-x")).not.toBe(initialX);
  await page.screenshot({ path: "screenshots/visual-consistency/city.png" });
  await page.getByLabel("Обозначения карты").click();
  await expect(page.locator(".map-legend-panel")).toContainText("Исправление проверяется");
  await page.getByLabel("Обозначения карты").click();
  const search = page.getByLabel("Поиск здания по номеру или названию");
  await search.fill("1");
  await page.locator(".task-search-results [role=option]").first().click();
  await expect(page.locator(".task-modal")).toBeVisible();
  await expect(page.getByRole("button", { name: "Перенести в другой спринт" })).toHaveCount(0);
  await page.getByRole("button", { name: "Закрыть", exact: true }).click();
  await expect(page.locator(".task-modal")).toHaveCount(0);
  await page.getByRole("button", { name: "Страна", exact: true }).click();
  const country = page.locator(".country-overview");
  await expect(country).toHaveAttribute("data-country-ready", "true", { timeout: 60_000 });
  await expect(country).toHaveAttribute("data-country-material-subdivisions", "2");
  await expect(page.locator(".map-level-transition")).toHaveCount(0);
  const before = await page.locator(".country-overview-raster").getAttribute("style");
  const cb = (await country.boundingBox())!;
  await page.mouse.move(cb.x + 200, cb.y + 100); await page.mouse.down(); await page.mouse.move(cb.x + 320, cb.y + 100, { steps: 8 }); await page.mouse.up();
  await expect.poll(() => page.locator(".country-overview-raster").getAttribute("style")).not.toBe(before);
  expect(await country.evaluate(node => getComputedStyle(node).backgroundImage)).toContain("data:image/png");
  await page.screenshot({ path: "screenshots/visual-consistency/country.png" });
  await page.getByRole("button", { name: "Планета", exact: true }).click();
  await expect(page.locator(".planet-atlas")).toHaveAttribute("data-planet-ready", "true", { timeout: 60_000 });
  expect(await page.locator(".planet-atlas clipPath rect").count()).toBeGreaterThan(20);
  await expect(page.locator(".planet-atlas clipPath ellipse")).toHaveCount(0);
  await expect(page.locator(".map-level-transition")).toHaveCount(0);
  await page.screenshot({ path: "screenshots/visual-consistency/planet.png" });
  await page.setViewportSize({ width: 390, height: 844 });
  await expect(page.getByRole("button", { name: "Районы", exact: true })).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBe(390);
  await page.screenshot({ path: "screenshots/visual-consistency/mobile.png" });
  expect(errors).toEqual([]);
});
