CREATE TABLE users (
  id text PRIMARY KEY,
  email text NOT NULL UNIQUE,
  name text NOT NULL,
  password_hash text NOT NULL,
  active_country_id text,
  created_at timestamptz NOT NULL
);

CREATE TABLE sessions (
  id text PRIMARY KEY,
  user_id text NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  token_hash text NOT NULL UNIQUE,
  expires_at timestamptz NOT NULL,
  created_at timestamptz NOT NULL
);
CREATE INDEX sessions_user_idx ON sessions(user_id);
CREATE INDEX sessions_expiry_idx ON sessions(expires_at);

CREATE TABLE countries (
  id text PRIMARY KEY,
  user_id text NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  name text NOT NULL,
  seed integer NOT NULL,
  world_version bigint NOT NULL DEFAULT 1,
  created_at timestamptz NOT NULL
);
CREATE INDEX countries_owner_idx ON countries(user_id);

CREATE TABLE country_members (
  country_id text NOT NULL REFERENCES countries(id) ON DELETE CASCADE,
  user_id text NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  role text NOT NULL CHECK(role IN ('OWNER', 'MEMBER', 'VIEWER')),
  invited_by_user_id text REFERENCES users(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL,
  PRIMARY KEY (country_id, user_id)
);
CREATE INDEX country_members_user_idx ON country_members(user_id, country_id);

ALTER TABLE users ADD CONSTRAINT users_active_country_fk
  FOREIGN KEY (active_country_id) REFERENCES countries(id) ON DELETE SET NULL DEFERRABLE INITIALLY DEFERRED;

CREATE TABLE mcp_tokens (
  id text PRIMARY KEY,
  country_id text NOT NULL REFERENCES countries(id) ON DELETE CASCADE,
  user_id text REFERENCES users(id) ON DELETE CASCADE,
  name text NOT NULL,
  token_hash text NOT NULL UNIQUE,
  token_prefix text NOT NULL,
  scopes_json jsonb NOT NULL,
  expires_at timestamptz,
  last_used_at timestamptz,
  revoked_at timestamptz,
  created_at timestamptz NOT NULL
);
CREATE INDEX mcp_tokens_user_active_idx ON mcp_tokens(user_id) WHERE revoked_at IS NULL;

CREATE TABLE projects (
  id text PRIMARY KEY, country_id text NOT NULL REFERENCES countries(id) ON DELETE CASCADE,
  name text NOT NULL, description text NOT NULL DEFAULT '', status text NOT NULL DEFAULT 'ACTIVE',
  city_q integer NOT NULL, city_r integer NOT NULL, boundary_json jsonb NOT NULL, created_at timestamptz NOT NULL
);
CREATE INDEX projects_country_idx ON projects(country_id);

CREATE TABLE sprints (
  id text PRIMARY KEY, project_id text NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  name text NOT NULL, goal text NOT NULL DEFAULT '', status text NOT NULL DEFAULT 'PLANNED',
  capacity_sp integer NOT NULL DEFAULT 14, district_json jsonb NOT NULL, color text NOT NULL, created_at timestamptz NOT NULL
);
CREATE INDEX sprints_project_idx ON sprints(project_id);
CREATE UNIQUE INDEX one_active_sprint_per_project ON sprints(project_id) WHERE status = 'ACTIVE';

CREATE TABLE tasks (
  id text PRIMARY KEY, project_id text NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  sprint_id text NOT NULL REFERENCES sprints(id) ON DELETE CASCADE, title text NOT NULL,
  description text NOT NULL DEFAULT '', estimate integer NOT NULL, priority text NOT NULL DEFAULT 'NORMAL',
  status text NOT NULL DEFAULT 'PLANNING', progress integer NOT NULL DEFAULT 0, due_at timestamptz,
  building_type text NOT NULL, platform_type text NOT NULL, origin_q integer NOT NULL, origin_r integer NOT NULL,
  footprint_json jsonb NOT NULL, created_at timestamptz NOT NULL, updated_at timestamptz NOT NULL
);
CREATE INDEX tasks_sprint_idx ON tasks(sprint_id);

CREATE TABLE task_comments (
  id text PRIMARY KEY, task_id text NOT NULL REFERENCES tasks(id) ON DELETE CASCADE,
  body text NOT NULL, actor text NOT NULL, created_at timestamptz NOT NULL
);

CREATE TABLE roads (
  country_id text NOT NULL REFERENCES countries(id) ON DELETE CASCADE,
  q integer NOT NULL, r integer NOT NULL, mask integer NOT NULL DEFAULT 0,
  structure text NOT NULL DEFAULT 'ROAD', PRIMARY KEY (country_id, q, r)
);

CREATE TABLE idempotency (
  country_id text NOT NULL REFERENCES countries(id) ON DELETE CASCADE,
  operation text NOT NULL, idempotency_key text NOT NULL, request_hash text NOT NULL,
  response_json jsonb NOT NULL, created_at timestamptz NOT NULL,
  PRIMARY KEY (country_id, operation, idempotency_key)
);

CREATE TABLE events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  country_id text NOT NULL REFERENCES countries(id) ON DELETE CASCADE,
  type text NOT NULL, world_version bigint NOT NULL, payload_json jsonb NOT NULL, created_at timestamptz NOT NULL
);
CREATE INDEX events_country_idx ON events(country_id, id);

CREATE TABLE cities_v3 (
  id text PRIMARY KEY, country_id text NOT NULL REFERENCES countries(id) ON DELETE CASCADE,
  name text NOT NULL, description text NOT NULL DEFAULT '', status text NOT NULL DEFAULT 'ACTIVE',
  center_x integer NOT NULL, center_y integer NOT NULL, bounds_json jsonb NOT NULL,
  style_id text NOT NULL, morphology text NOT NULL DEFAULT 'BALANCED', created_at timestamptz NOT NULL
);
CREATE INDEX cities_v3_country_idx ON cities_v3(country_id, created_at, id);

CREATE TABLE districts_v3 (
  id text PRIMARY KEY, city_id text NOT NULL REFERENCES cities_v3(id) ON DELETE CASCADE,
  name text NOT NULL, goal text NOT NULL DEFAULT '', status text NOT NULL DEFAULT 'PLANNED',
  capacity_sp integer NOT NULL DEFAULT 14, cells_json jsonb NOT NULL, lots_json jsonb NOT NULL,
  growth_direction text NOT NULL, archetype text NOT NULL DEFAULT 'MIXED_URBAN', color text NOT NULL,
  created_at timestamptz NOT NULL
);
CREATE INDEX districts_v3_city_idx ON districts_v3(city_id, created_at);
CREATE UNIQUE INDEX one_active_district_per_city_v3 ON districts_v3(city_id) WHERE status = 'ACTIVE';

CREATE TABLE tasks_v3 (
  id text PRIMARY KEY, city_id text NOT NULL REFERENCES cities_v3(id) ON DELETE CASCADE,
  district_id text NOT NULL REFERENCES districts_v3(id) ON DELETE CASCADE,
  title text NOT NULL, description text NOT NULL DEFAULT '', estimate integer NOT NULL,
  priority text NOT NULL DEFAULT 'NORMAL', status text NOT NULL DEFAULT 'PLANNING', progress integer NOT NULL DEFAULT 0,
  due_at timestamptz, building_type text NOT NULL, platform_type text NOT NULL,
  origin_x integer NOT NULL, origin_y integer NOT NULL, footprint_json jsonb NOT NULL,
  entrance_x integer, entrance_y integer, access_json jsonb NOT NULL DEFAULT '[]'::jsonb,
  access_kind text NOT NULL DEFAULT 'PATH', creator_user_id text REFERENCES users(id) ON DELETE SET NULL,
  assignee_user_id text REFERENCES users(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL, updated_at timestamptz NOT NULL
);
CREATE INDEX tasks_v3_district_idx ON tasks_v3(district_id, created_at);
CREATE INDEX tasks_v3_city_idx ON tasks_v3(city_id, created_at);

CREATE TABLE task_comments_v3 (
  id text PRIMARY KEY, task_id text NOT NULL REFERENCES tasks_v3(id) ON DELETE CASCADE,
  body text NOT NULL, actor text NOT NULL, created_at timestamptz NOT NULL
);

CREATE TABLE task_events_v7 (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  task_id text NOT NULL REFERENCES tasks_v3(id) ON DELETE CASCADE,
  actor_user_id text REFERENCES users(id) ON DELETE SET NULL, actor_label text NOT NULL,
  event_type text NOT NULL, details_json jsonb NOT NULL DEFAULT '{}'::jsonb, created_at timestamptz NOT NULL
);
CREATE INDEX task_events_v7_task_idx ON task_events_v7(task_id, id);

CREATE TABLE roads_v3 (
  country_id text NOT NULL REFERENCES countries(id) ON DELETE CASCADE,
  x integer NOT NULL, y integer NOT NULL, mask integer NOT NULL DEFAULT 0,
  structure text NOT NULL DEFAULT 'ROAD', road_class text NOT NULL DEFAULT 'LOCAL',
  PRIMARY KEY (country_id, x, y)
);
CREATE INDEX roads_v3_country_position_idx ON roads_v3(country_id, x, y);

CREATE TABLE world_features_v6 (
  id text PRIMARY KEY, country_id text NOT NULL REFERENCES countries(id) ON DELETE CASCADE,
  city_id text REFERENCES cities_v3(id) ON DELETE CASCADE, kind text NOT NULL,
  asset_kind text NOT NULL, asset_key text NOT NULL, origin_x integer NOT NULL, origin_y integer NOT NULL,
  footprint_json jsonb NOT NULL, orientation text NOT NULL, access_json jsonb NOT NULL DEFAULT '[]'::jsonb,
  created_at timestamptz NOT NULL
);
CREATE INDEX world_features_v6_country_position_idx ON world_features_v6(country_id, origin_x, origin_y);

CREATE TABLE world_chunk_entities_v11 (
  country_id text NOT NULL REFERENCES countries(id) ON DELETE CASCADE,
  chunk_x integer NOT NULL, chunk_y integer NOT NULL,
  entity_kind text NOT NULL CHECK(entity_kind IN ('DISTRICT', 'TASK', 'FEATURE')),
  entity_id text NOT NULL,
  PRIMARY KEY (country_id, chunk_x, chunk_y, entity_kind, entity_id)
);
CREATE INDEX world_chunk_entities_v11_lookup_idx
  ON world_chunk_entities_v11(country_id, entity_kind, chunk_x, chunk_y);

CREATE FUNCTION refresh_district_chunks_v14() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE target_id text;
BEGIN
  target_id := CASE WHEN TG_OP = 'DELETE' THEN OLD.id ELSE NEW.id END;
  DELETE FROM world_chunk_entities_v11 WHERE entity_kind = 'DISTRICT' AND entity_id = target_id;
  IF TG_OP <> 'DELETE' THEN
    INSERT INTO world_chunk_entities_v11(country_id, chunk_x, chunk_y, entity_kind, entity_id)
    SELECT c.country_id, floor((cell->>'x')::numeric / 64)::integer,
      floor((cell->>'y')::numeric / 64)::integer, 'DISTRICT', NEW.id
    FROM cities_v3 c CROSS JOIN LATERAL jsonb_array_elements(NEW.cells_json) cell
    WHERE c.id = NEW.city_id ON CONFLICT DO NOTHING;
  END IF;
  IF TG_OP = 'DELETE' THEN RETURN OLD; END IF;
  RETURN NEW;
END $$;
CREATE TRIGGER districts_v3_chunks_insert_v14 AFTER INSERT ON districts_v3
  FOR EACH ROW EXECUTE FUNCTION refresh_district_chunks_v14();
CREATE TRIGGER districts_v3_chunks_update_v14 AFTER UPDATE OF cells_json, city_id ON districts_v3
  FOR EACH ROW EXECUTE FUNCTION refresh_district_chunks_v14();
CREATE TRIGGER districts_v3_chunks_delete_v14 AFTER DELETE ON districts_v3
  FOR EACH ROW EXECUTE FUNCTION refresh_district_chunks_v14();

CREATE FUNCTION refresh_task_chunks_v14() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE target_id text;
BEGIN
  target_id := CASE WHEN TG_OP = 'DELETE' THEN OLD.id ELSE NEW.id END;
  DELETE FROM world_chunk_entities_v11 WHERE entity_kind = 'TASK' AND entity_id = target_id;
  IF TG_OP <> 'DELETE' THEN
    INSERT INTO world_chunk_entities_v11(country_id, chunk_x, chunk_y, entity_kind, entity_id)
    SELECT c.country_id, floor((cell->>'x')::numeric / 64)::integer,
      floor((cell->>'y')::numeric / 64)::integer, 'TASK', NEW.id
    FROM cities_v3 c CROSS JOIN LATERAL jsonb_array_elements(NEW.footprint_json || NEW.access_json) cell
    WHERE c.id = NEW.city_id ON CONFLICT DO NOTHING;
  END IF;
  IF TG_OP = 'DELETE' THEN RETURN OLD; END IF;
  RETURN NEW;
END $$;
CREATE TRIGGER tasks_v3_chunks_insert_v14 AFTER INSERT ON tasks_v3
  FOR EACH ROW EXECUTE FUNCTION refresh_task_chunks_v14();
CREATE TRIGGER tasks_v3_chunks_update_v14 AFTER UPDATE OF footprint_json, access_json, city_id ON tasks_v3
  FOR EACH ROW EXECUTE FUNCTION refresh_task_chunks_v14();
CREATE TRIGGER tasks_v3_chunks_delete_v14 AFTER DELETE ON tasks_v3
  FOR EACH ROW EXECUTE FUNCTION refresh_task_chunks_v14();

CREATE FUNCTION refresh_feature_chunks_v14() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE target_id text;
BEGIN
  target_id := CASE WHEN TG_OP = 'DELETE' THEN OLD.id ELSE NEW.id END;
  DELETE FROM world_chunk_entities_v11 WHERE entity_kind = 'FEATURE' AND entity_id = target_id;
  IF TG_OP <> 'DELETE' THEN
    INSERT INTO world_chunk_entities_v11(country_id, chunk_x, chunk_y, entity_kind, entity_id)
    SELECT NEW.country_id, floor((cell->>'x')::numeric / 64)::integer,
      floor((cell->>'y')::numeric / 64)::integer, 'FEATURE', NEW.id
    FROM jsonb_array_elements(NEW.footprint_json || NEW.access_json) cell ON CONFLICT DO NOTHING;
  END IF;
  IF TG_OP = 'DELETE' THEN RETURN OLD; END IF;
  RETURN NEW;
END $$;
CREATE TRIGGER world_features_v6_chunks_insert_v14 AFTER INSERT ON world_features_v6
  FOR EACH ROW EXECUTE FUNCTION refresh_feature_chunks_v14();
CREATE TRIGGER world_features_v6_chunks_update_v14 AFTER UPDATE OF footprint_json, access_json, country_id ON world_features_v6
  FOR EACH ROW EXECUTE FUNCTION refresh_feature_chunks_v14();
CREATE TRIGGER world_features_v6_chunks_delete_v14 AFTER DELETE ON world_features_v6
  FOR EACH ROW EXECUTE FUNCTION refresh_feature_chunks_v14();
